[package]
name = "Alogorithm-Visuals"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
console_error_panic_hook = "0.1.7"
gloo-timers = { version = "0.3", features = ["futures"] }
leptos = { version = "0.8.15", features = ["csr"] }
log = "0.4.29"
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-logger = "0.2.0"

[dev-dependencies]
wasm-bindgen-test = "0.3"
